### PR TITLE
Bool overload fix 03

### PR DESCRIPTION
**Pull request by djerius**
This is a much cleaner version of PR #116.  The resultant code is the same, but it should be much easier to review the changes.

### CODE REVIEW

**Comment by djerius** [comment]
For completeness, this relates to #115

**Comment by exodist** [comment]
So, the changes to the .pm files all look good/sane. But I am wondering why you made the changes to the tests. It looks like you made the changes to future-proof, so that future edits to the code would not accidentally re-introduce the overload bug.

I think future-proof testing is important, but I am not a fan of the way you did it here. I would rather have a completely new test file in .t. In the .t file you can load all compare classes, inject overloading into them, then test them all. I would rather not have the current tests add the injecting.

I think once the testing issue is resolved I will be ready to merge this and do another downstream testing run.

Sorry it took me so long to get back to you on this.

**Comment by exodist** [comment]
I went ahead and merged your code changes, but not your test changes. I wrote my own .t file to test this: https://github.com/Test-More/Test2-Suite/blob/04bd65978cb77b6feac7d2c63884aef5978aed03/t/regression/132-bool.t

**Comment by exodist** [comment]
I uploaded a -TRIAL release of this for testing.

**Comment by exodist** [comment]
hmm, looks like it is broken on 5.8 and 5.10

**Comment by exodist** [comment]
ok, new fix, and new trial released.

**Comment by djerius** [comment]
My rationale for the approach I took was that a separate test for the overloading bug would  have to be as comprehensive in its code coverage as the full test suite, and would have to be updated as new features were added to the code. 

The code base is complex, and it's not a minor task to determine how to trigger a particular execution path.  I prefer behavior based, non-intrusive testing, but because I don't have a full picture of how various components interact, it's difficult to construct a comprehensive test suite. Piggybacking on the full test suite was the most straightforward means of doing so.  A significant number of the fixes were discovered by using the entire test suite, so it was, in any case, a useful approach for me.

**Comment by exodist** [comment]
My test file essentially does what your test changes did, but in a contained way. It still runs the full tests for all the comparisons, with the bool overload in place, but also lets the tests run normally without it.

https://github.com/Test-More/Test2-Suite/blob/04bd65978cb77b6feac7d2c63884aef5978aed03/t/regression/132-bool.t

**Comment by djerius** [comment]
Sorry, I hadn't read ahead in my email to see your later comment about your
added test.  I hadn't thought of that approach.

Thanks for merging.

**Pull request closed without merging**
