### PR TITLE
Add calls

### LINKED ISSUE #158: Add behaviour verification to Test2::Mock objects
# Summary

This is a feature request for allowing calls to a Test2::Mock object to be stored/returned. This is intended to be used by test scripts using behaviour verification to check the order and content of calls to a mocked object during a test run. What I have in mind is something similar to the implementation of [Test::MockObject](https://metacpan.org/pod/Test::MockObject).

# Initial Proposal
```perl
$mock->track('foo' [, sub{...} ]);

my $mock = mock obj => (
    track => [ foo => sub { ... } ],
); 
```

Records calls made to method 'foo', where the sub is optional if you want to
track the calls to a method defined another way.

```perl
my $calls = $mock->calls('foo');
```

Returns calls made via method 'foo' on a mocked object.

### PR DESCRIPTION
**Pull request by robkinyon**
Adds subroutine call logging.

This fixes #158

### CODE REVIEW

**Comment by exodist** [comment]
Still need to give it a deeper review, but one request: Please make this be a feature you need to turn on, not on by default. My reasoning is that the calls are logged storing all arguments, which means it could have side effects of preventing other objects (ones passed in) from being garbage collected when expected, which could break existing code. It also means consuming more memory without any benefit for existing code.

Maybe something like:
```
my $c = mock 'Foo::Bar' => (
    override => [ foo => sub { ... } ],
    log_calls => 1, # Turn on call logging
);

$c->log_calls($bool); # Turn it on/off
```

**Comment by exodist** [comment]
finally had a chance to look at this. I am curious why you store the calls in a persistent variable instead of an attribute of the mock instance?

**Comment by robkinyon** [comment]
I originally wrote the code as (e.g., line 315 of `_parse_inject()`)
```
    return ('&', $param, sub {
        $self->_log_call($param, @_);
        goto &$arg;
    }) if ref($arg) && reftype($arg) eq 'CODE';
```
But, this didn't work because the callback's scratchpad was holding a reference to `$self` and that prevented object destruction from working as expected. So, this forced me to pass the refaddr in instead of the object. Once I had to do that, then there's no way to re-hydrate `$self` from the refaddr.

This should have been explained in the comments on line 520 for `_log_call()` - are those comments not explanatory enough?

**Comment by robkinyon** [comment]
ping

**Comment by exodist** [comment]
I need to make some more time to look into this. The persistent var and what you said about holding onto $self bothers me, but it might not when I fully grok the code, which just means making the time to do so, sorry I have been so busy lately. I am hoping I can make time next week to look at this deeper, and possibly either make a new suggestion tot he PR, or merge it.

**Comment by robkinyon** [comment]
ping.

**Comment by exodist** [comment]
I have not forgotten. I will try to make time to look at this on Saturday.

**Comment by robkinyon** [comment]
ping.

**Comment by exodist** [comment]
I have looked a bit deeper and I am still bothered by the persistent variable. Reading the changes makes me feel like some dirty hacks were required here, and that is probably the fault of my original code, not a statement against you in any way. I feel like some deeper changes are needed to the mocking module to make the implementation of this feature cleaner. I am at the Perl Toolchain Summit right now, so I am going to take some time to dive in and see what I can do to fix my code so that a feature like this can be implemented cleanly.

**Comment by exodist** [comment]
@robkinyon 
https://github.com/Test-More/Test2-Suite/pull/184

The above is my super quick implementation of this feature. Please review that and let me know if it meets your requirements, or if I missed something you need. This implementation avoids the need for a persistent variable outside the mock object itself. I think it also has a cleaner interface that better matches what I already have (not a criticism of your work, what you had was good, but just not quite in-line with the rest of the mock tools).

**Comment by robkinyon** [comment]
@exodist No criticism taken. This is why you're the DFL and I'm the PR submitter - you understand your architecture far better than I ever could.

I left comments in #184 and am happy to close this PR in preference to it.

**Pull request closed without merging**
