### PR TITLE
Merge Test2::Workflow into Test2::Suite #94

### PR DESCRIPTION
**Pull request by kspice**
This was done as part of the CPAN Pull Request Challenge.

### CODE REVIEW

**Comment by exodist** [comment]
This looks good, it appears the only real change necessary was removing the '$' from the end of a test regex? Nice!

I have one request to make here. All .pm files in Test2-Suite have the $VERSION set, and all have the same version. Test2::Suite is at a higher version than Test2::Workflow. Can you please add the $VERSION to the top of all the added .pm files? Also make sure they all use the same version as the test of Test2::Suite.

Thanks!

**Comment by exodist** [comment]
So, I just realized this completely wipes out the git history from Test2::Workflow. I want to merge the repos with history, which can be done by merging the other repo as though it were a remote repo.

That said, the work you have here to make sure everything works/passes is very helpful. Do not worry about making the other changes I asked for, I will do the big merge, and then apply your commit on top of it.

**Comment by exodist** [comment]
I merged your fixes and Test2::Workflow. Thanks!

**Comment by kspice** [comment]
Awesome, thanks for letting me know! Really good point about the git 
history, it didn't even occur to me.

Sorry for the slow reply - I'm helping organise the London Perl Workshop 
(which is tomorrow!) - this is a great start to the weekend :)

**Pull request closed without merging**
